name: Release Service

on:
  push:
    tags:
      - 'v*.*'

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Prepare StartOS SDK
        uses: start9labs/sdk@v2

      - name: Checkout services repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the service package
        id: build
        run: |
          start-cli init
          RUST_LOG=debug RUST_BACKTRACE=1 make
          PACKAGE_ID=$(grep -o "id: '[^']*'" startos/manifest.ts | sed "s/id: '\([^']*\)'/\1/")
          PACKAGE_TITLE=$(grep -o "title: '[^']*'" startos/manifest.ts | sed "s/title: '\([^']*\)'/\1/")
          echo "package_id=${PACKAGE_ID}" >> $GITHUB_ENV
          echo "package_title=${PACKAGE_TITLE}" >> $GITHUB_ENV
          printf "\n SHA256SUM: $(sha256sum ${PACKAGE_ID}.s9pk) \n"
        shell: bash

      - name: Generate sha256 checksum
        run: |
          sha256sum ${{ env.package_id }}.s9pk > ${{ env.package_id }}.s9pk.sha256
        shell: bash

      - name: Generate changelog
        run: |
          echo "## What's Changed" > change-log.txt

          # Find the latest version file in startos/versions/
          LATEST_VERSION_FILE=$(find startos/versions/ -name "v*.ts" | sort -V | tail -n 1)
          echo "" >> change-log.txt

          # Extract release notes using a more precise approach for TypeScript
          RELEASE_NOTES=$(grep -o "releaseNotes: '[^']*'" "${LATEST_VERSION_FILE}" | sed "s/releaseNotes: '\([^']*\)'/\1/")
          if [ -z "$RELEASE_NOTES" ]; then
            # Try with double quotes if single quotes didn't work
            RELEASE_NOTES=$(grep -o 'releaseNotes: "[^"]*"' "${LATEST_VERSION_FILE}" | sed 's/releaseNotes: "\([^"]*\)"/\1/')
          fi

          echo "${RELEASE_NOTES}" >> change-log.txt

          echo "## SHA256 Hash" >> change-log.txt
          echo '```' >> change-log.txt
          sha256sum ${{ env.package_id }}.s9pk >> change-log.txt
          echo '```' >> change-log.txt
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.package_title }} ${{ github.ref_name }}
          prerelease: true
          body_path: change-log.txt
          files: |
            ./${{ env.package_id }}.s9pk
            ./${{ env.package_id }}.s9pk.sha256

      # - name: Publish to Registry
      #   env:
      #     S9USER: ${{ secrets.S9USER }}
      #     S9PASS: ${{ secrets.S9PASS }}
      #     S9REGISTRY: ${{ secrets.S9REGISTRY }}
      #   run: |
      #     if [[ -z "$S9USER" || -z "$S9PASS" || -z "$S9REGISTRY" ]]; then
      #       echo "Publish skipped: missing registry credentials."
      #     else
      #       start-cli publish https://$S9USER:$S9PASS@$S9REGISTRY ${{ env.package_id }}.s9pk
      #     fi
